### ISSUE TITLE
Thanks & question about moving auth to PostgreSQL

### ISSUE THREAD

**Issue by gh0st-work** [CrazyCatCZ/Article-Django-React-App#2]
Hi!
Very cool repository, thank you very much, it's helped me with my personal project. Can you tell me, I want to move some of your code to my app, but I have PostgreSQL on the deployment server and already have a database with users, can I somehow rewrite to make only auth under PostgreSQL? If so, tell me briefly how it works, I just did not work with graphql at all. Thanks for the cool code, very helpful!

**Comment by plechipt** [comment]
Hey
I am glad this project helped you. I am using JWT authentication with httponly cookies. Every request it is checking if access token is expired and if so, it refresh access token and generates new refresh token

Link: https://django-graphql-jwt.domake.io/en/latest/authentication.html#per-cookie

**Comment by gh0st-work** [comment]
Thank you very much! I soon have planned investments in my project, if there are not enough developers, I will offer you) I now live in the Czech Republic too.
